# Generated by Django 6.1.1 on 2026-09-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('CONTACT_FOUND', 'Contact Found'), ('CONTACTED', 'Contacted'), ('RESUME_SENT', 'Resume Sent'), ('RESUME_ACCEPTED', 'Resume Accepted'), ('REPLIED', 'Replied'), ('WILL_REFER', 'Willing to Refer'), ('REFERRAL_GIVEN', 'Referral Given'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer Received'), ('HIRED', 'Hired'), ('REJECTED', 'Passed / Rejected'), ('NO_RESPONSE', 'No Response'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed')], db_index=True, default='CONTACT_FOUND', max_length=50)),
                ('connection_type', models.CharField(default='PRIMARY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='relationships.relationship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='relationships.relationship')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(db_index=True, max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='relationships.relationship')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user', 'current_status'], name='relationshi_user_id_ec750c_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user', 'person'], name='relationshi_user_id_b9d4be_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user', 'created_at'], name='relationshi_user_id_b67af3_idx'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('user', 'person'), name='unique_user_person_relationship'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['relationship', 'timestamp'], name='relationshi_relatio_609ec5_idx'),
        ),
    ]
