# Generated by Django 6.1.1 on 2026-09-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FOLLOW_UP', 'Follow Up Required'), ('REFERRAL_OPPORTUNITY', 'Referral Opportunity Detected'), ('APPLICATION_ACTION', 'Application Action Required'), ('RELATIONSHIP_OPPORTUNITY', 'Relationship Opportunity'), ('NETWORK_GAP', 'Network Gap Identified'), ('PIPELINE_RISK', 'Pipeline Risk'), ('COMPANY_OPPORTUNITY', 'Company Opportunity'), ('INTERVIEW_PREPARATION', 'Interview Preparation'), ('APPLICATION_STALE', 'Stale Application'), ('CONTACT_STALE', 'Stale Contact Interaction'), ('REFERRAL_MISSING', 'Referral Missing'), ('GENERAL_INSIGHT', 'General Career Insight')], db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority')], db_index=True, default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reason', models.TextField(help_text='Explainable data-driven reason for recommendation')),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('deduplication_key', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VIEWED', 'Viewed'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed'), ('SNOOZED', 'Snoozed')], db_index=True, default='NEW', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='intelligence.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEWED', 'Viewed'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed'), ('SNOOZED', 'Snoozed'), ('ACTION_TAKEN', 'Action Taken')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intelligence.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'status'], name='intelligenc_user_id_2bd797_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'priority'], name='intelligenc_user_id_10d5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'deduplication_key'], name='intelligenc_user_id_44e3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'entity_type', 'entity_id'], name='intelligenc_user_id_8debb3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='intelligenc_user_id_5ffcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='intelligenc_user_id_cbd7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['user', 'event_type'], name='intelligenc_user_id_7a6d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['recommendation', 'created_at'], name='intelligenc_recomme_d639e9_idx'),
        ),
    ]
