import type { StatusConfigItem } from '../types';

export const APPLICATION_STATUS_CONFIG: StatusConfigItem[] = [
  {
    key: 'SAVED',
    label: 'Saved',
    category: 'Discovery',
    order: 1,
    color: '#94A3B8',
    bgClass: 'bg-slate-100',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-300',
  },
  {
    key: 'APPLIED',
    label: 'Applied',
    category: 'Active',
    order: 2,
    color: '#3B82F6',
    bgClass: 'bg-blue-100',
    textClass: 'text-blue-700',
    borderClass: 'border-blue-500',
  },
  {
    key: 'REFERRAL_REQUESTED',
    label: 'Referral Requested',
    category: 'Referral',
    order: 3,
    color: '#6366F1',
    bgClass: 'bg-indigo-100',
    textClass: 'text-indigo-700',
    borderClass: 'border-indigo-500',
  },
  {
    key: 'REFERRAL_GIVEN',
    label: 'Referral Given',
    category: 'Referral',
    order: 4,
    color: '#8B5CF6',
    bgClass: 'bg-purple-100',
    textClass: 'text-purple-700',
    borderClass: 'border-purple-500',
  },
  {
    key: 'SCREENING',
    label: 'Initial Screening',
    category: 'Interview',
    order: 5,
    color: '#38BDF8',
    bgClass: 'bg-sky-100',
    textClass: 'text-sky-700',
    borderClass: 'border-sky-400',
  },
  {
    key: 'INTERVIEW',
    label: 'Interviewing',
    category: 'Interview',
    order: 6,
    color: '#10B981',
    bgClass: 'bg-emerald-100',
    textClass: 'text-emerald-700',
    borderClass: 'border-emerald-500',
  },
  {
    key: 'TECHNICAL_INTERVIEW',
    label: 'Technical Interview',
    category: 'Interview',
    order: 7,
    color: '#0D9488',
    bgClass: 'bg-teal-100',
    textClass: 'text-teal-800',
    borderClass: 'border-teal-600',
  },
  {
    key: 'HR_INTERVIEW',
    label: 'HR Interview',
    category: 'Interview',
    order: 8,
    color: '#0284C7',
    bgClass: 'bg-sky-100',
    textClass: 'text-sky-800',
    borderClass: 'border-sky-600',
  },
  {
    key: 'OFFER',
    label: 'Offer Received',
    category: 'Success',
    order: 9,
    color: '#22C55E',
    bgClass: 'bg-green-100',
    textClass: 'text-green-700',
    borderClass: 'border-green-500',
  },
  {
    key: 'HIRED',
    label: 'Hired',
    category: 'Success',
    order: 10,
    color: '#059669',
    bgClass: 'bg-emerald-200',
    textClass: 'text-emerald-900',
    borderClass: 'border-emerald-600',
  },
  {
    key: 'REJECTED',
    label: 'Rejected',
    category: 'Closed',
    order: 11,
    color: '#F43F5E',
    bgClass: 'bg-rose-100',
    textClass: 'text-rose-700',
    borderClass: 'border-rose-500',
  },
  {
    key: 'WITHDRAWN',
    label: 'Withdrawn',
    category: 'Closed',
    order: 12,
    color: '#64748B',
    bgClass: 'bg-slate-200',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-400',
  },
  {
    key: 'CLOSED',
    label: 'Closed',
    category: 'Closed',
    order: 13,
    color: '#475569',
    bgClass: 'bg-slate-200',
    textClass: 'text-slate-800',
    borderClass: 'border-slate-600',
  }
];

export const getAppStatusConfig = (key: string): StatusConfigItem => {
  return APPLICATION_STATUS_CONFIG.find(s => s.key === key) || APPLICATION_STATUS_CONFIG[0];
};

export const CONTACT_ROLE_CONFIG: Record<string, { label: string; bg: string; text: string }> = {
  CONTACT: { label: 'General Contact', bg: 'bg-slate-100', text: 'text-slate-700' },
  REFERRAL_CONTACT: { label: 'Referral Contact', bg: 'bg-purple-100', text: 'text-purple-700' },
  RECRUITER: { label: 'Recruiter', bg: 'bg-blue-100', text: 'text-blue-700' },
  HIRING_MANAGER: { label: 'Hiring Manager', bg: 'bg-indigo-100', text: 'text-indigo-700' },
  INTERVIEWER: { label: 'Interviewer', bg: 'bg-emerald-100', text: 'text-emerald-700' },
};
