import type { StatusConfigItem } from '../types';

export const STATUS_CONFIG: StatusConfigItem[] = [
  {
    key: 'CONTACT_FOUND',
    label: 'Contact Found',
    category: 'Discovery',
    order: 1,
    color: '#94A3B8',
    bgClass: 'bg-slate-100',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-300',
  },
  {
    key: 'CONTACTED',
    label: 'Contacted',
    category: 'Outreach',
    order: 2,
    color: '#38BDF8',
    bgClass: 'bg-sky-100',
    textClass: 'text-sky-700',
    borderClass: 'border-sky-400',
  },
  {
    key: 'RESUME_SENT',
    label: 'Resume Sent',
    category: 'Outreach',
    order: 3,
    color: '#3B82F6',
    bgClass: 'bg-blue-100',
    textClass: 'text-blue-700',
    borderClass: 'border-blue-500',
  },
  {
    key: 'RESUME_ACCEPTED',
    label: 'Resume Accepted',
    category: 'Engagement',
    order: 4,
    color: '#14B8A6',
    bgClass: 'bg-teal-100',
    textClass: 'text-teal-700',
    borderClass: 'border-teal-500',
  },
  {
    key: 'REPLIED',
    label: 'Replied',
    category: 'Engagement',
    order: 5,
    color: '#F97316',
    bgClass: 'bg-orange-100',
    textClass: 'text-orange-700',
    borderClass: 'border-orange-500',
  },
  {
    key: 'WILL_REFER',
    label: 'Willing to Refer',
    category: 'Referral',
    order: 6,
    color: '#6366F1',
    bgClass: 'bg-indigo-100',
    textClass: 'text-indigo-700',
    borderClass: 'border-indigo-500',
  },
  {
    key: 'REFERRAL_GIVEN',
    label: 'Referral Given',
    category: 'Referral',
    order: 7,
    color: '#8B5CF6',
    bgClass: 'bg-purple-100',
    textClass: 'text-purple-700',
    borderClass: 'border-purple-500',
  },
  {
    key: 'INTERVIEW',
    label: 'Interviewing',
    category: 'Active',
    order: 8,
    color: '#10B981',
    bgClass: 'bg-emerald-100',
    textClass: 'text-emerald-700',
    borderClass: 'border-emerald-500',
  },
  {
    key: 'OFFER',
    label: 'Offer Received',
    category: 'Active',
    order: 9,
    color: '#22C55E',
    bgClass: 'bg-green-100',
    textClass: 'text-green-700',
    borderClass: 'border-green-500',
  },
  {
    key: 'HIRED',
    label: 'Hired',
    category: 'Success',
    order: 10,
    color: '#059669',
    bgClass: 'bg-emerald-200',
    textClass: 'text-emerald-800',
    borderClass: 'border-emerald-600',
  },
  {
    key: 'REJECTED',
    label: 'Passed / Rejected',
    category: 'Closed',
    order: 11,
    color: '#F43F5E',
    bgClass: 'bg-rose-100',
    textClass: 'text-rose-700',
    borderClass: 'border-rose-500',
  },
  {
    key: 'NO_RESPONSE',
    label: 'No Response',
    category: 'Closed',
    order: 12,
    color: '#64748B',
    bgClass: 'bg-slate-200',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-400',
  },
  {
    key: 'NOT_INTERESTED',
    label: 'Not Interested',
    category: 'Closed',
    order: 13,
    color: '#71717A',
    bgClass: 'bg-zinc-100',
    textClass: 'text-zinc-700',
    borderClass: 'border-zinc-400',
  },
  {
    key: 'CLOSED',
    label: 'Closed',
    category: 'Closed',
    order: 14,
    color: '#475569',
    bgClass: 'bg-slate-200',
    textClass: 'text-slate-800',
    borderClass: 'border-slate-600',
  }
];

export const getStatusConfig = (key: string): StatusConfigItem => {
  return STATUS_CONFIG.find(s => s.key === key) || STATUS_CONFIG[0];
};
