# Generated by Django 6.1.1 on 2026-09-30 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('employment_type', models.CharField(blank=True, default='Full-time', max_length=50)),
                ('source', models.CharField(blank=True, default='LinkedIn', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('REFERRAL_REQUESTED', 'Referral Requested'), ('REFERRAL_GIVEN', 'Referral Given'), ('SCREENING', 'Initial Screening'), ('INTERVIEW', 'Interviewing'), ('TECHNICAL_INTERVIEW', 'Technical Interview'), ('HR_INTERVIEW', 'HR Interview'), ('OFFER', 'Offer Received'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], db_index=True, default='SAVED', max_length=50)),
                ('applied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.jobposition')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_role', models.CharField(choices=[('CONTACT', 'General Contact'), ('REFERRAL_CONTACT', 'Referral Contact'), ('RECRUITER', 'Recruiter / Talent Partner'), ('HIRING_MANAGER', 'Hiring Manager'), ('INTERVIEWER', 'Interviewer')], default='CONTACT', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_contacts', to='applications.application')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_contacts', to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'person'), name='unique_application_person_contact')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(db_index=True, max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['application', 'timestamp'], name='application_applica_1843f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'current_status'], name='application_user_id_d961f7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'applied_at'], name='application_user_id_84c807_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'created_at'], name='application_user_id_4e48e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job_position'), name='unique_user_application'),
        ),
    ]
